export const POLICIES = {
  refund: {
    title: "Refund Policy",
    content: `We have a 30-day return policy, which means you have 30 days after receiving your item to request a return.\n\nTo be eligible for a return, your item must be in the same condition that you received it, unworn or unused, with tags, and in its original packaging. You’ll also need the receipt or proof of purchase.\n\nTo start a return, you can contact us at conceptclothing.pt@gmail.com. Please note that returns will need to be sent to the following address: [Rua S. Miguel Roriz, n.º 1508, 4750-650 Barcelos, Portugal]\n\nIf your return is accepted, we’ll send you a return shipping label, as well as instructions on how and where to send your package. Items sent back to us without first requesting a return will not be accepted.\n\nDamages and issues\nPlease inspect your order upon reception and contact us immediately if the item is defective, damaged or if you receive the wrong item, so that we can evaluate the issue and make it right.\n\nExceptions / non-returnable items\nCertain types of items cannot be returned, like perishable goods, custom products, and personal care goods. We also do not accept returns for hazardous materials, flammable liquids, or gases. Unfortunately, we cannot accept returns on sale items or gift cards.\n\nExchanges\nThe fastest way to ensure you get what you want is to return the item you have, and once the return is accepted, make a separate purchase for the new item.\n\nEuropean Union 14 day cooling off period\nNotwithstanding the above, if the merchandise is being shipped into the European Union, you have the right to cancel or return your order within 14 days, for any reason and without a justification. Your item must be in the same condition that you received it, unworn or unused, with tags, and in its original packaging.\n\nRefunds\nWe will notify you once we’ve received and inspected your return, and let you know if the refund was approved or not. If approved, you’ll be automatically refunded on your original payment method within 10 business days. Please remember it can take some time for your bank or credit card company to process and post the refund too.`
  },
  shipping: {
    title: "Shipping Policy",
    content: `All orders are processed on the next business day after payment confirmation.\n\nMainland Portugal\nStandard Shipping (CTT) - €3.50 (no tracking)\nRegistered Shipping (CTT) - €5.50 (tracking number provided)\n\nEuropean Union\nInternational Standard Tracked - €8.50\nInternational Premium Tracked - €18.00\n\nUK and Rest of the World\nInternational Standard - €18.00\nInternational Tracked - €25.00\n\nDelivery times are estimates and may vary due to external factors such as customs or postal service strikes. Concept is not responsible for delays caused by shipping carriers.\n\nFor shipping-related questions, please contact us at conceptclothing.pt@gmail.com.`
  },
  privacy: {
    title: "Privacy Policy",
    content: `Your privacy is critically important to us.\n\nAt Concept, we have a few fundamental principles:\n- We are thoughtful about the personal information we ask you to provide and the personal information that we collect about you through the operation of our services.\n- We store personal information for only as long as we have a reason to keep it.\n- We aim for full transparency on how we gather, use, and share your personal information.\n\nWe use secure third-party services like Stripe for payment processing and Supabase for database management. Your credit card information is never stored directly on our servers; it is securely processed by Stripe.\n\nIf you have any questions about accessing or correcting your personal data, please contact us at conceptclothing.pt@gmail.com.`
  },
  terms: {
    title: "Terms of Service",
    content: `OVERVIEW\nWelcome to Concept! The terms “we”, “us” and “our” refer to Concept. Concept operates this store and website, including all related information, content, features, tools, products and services in order to provide you, the customer, with a curated shopping experience.\n\nSECTION 1 - ACCESS AND ACCOUNT\nBy agreeing to these Terms of Service, you represent that you are at least the age of majority in your country of residence. You are solely responsible for maintaining the security of your account credentials and for all of your account activity.\n\nSECTION 2 - OUR PRODUCTS\nWe have made every effort to provide an accurate representation of our products and services. However, please note that colors or product appearance may differ from how they may appear on your screen.\n\nSECTION 3 - ORDERS\nWhen you place an order, you are making an offer to purchase. Concept reserves the right to accept or decline your order for any reason at its discretion. We must receive and process your payment before your order is accepted.\n\nSECTION 4 - PRICES AND BILLING\nPrices, discounts and promotions are subject to change without notice. The price charged for a product or service will be the price in effect at the time the order is placed.\n\nSECTION 5 - CONTACT INFORMATION\nQuestions about the Terms of Service should be sent to us at conceptclothing.pt@gmail.com.`
  },
  legal: {
    title: "Legal Notice",
    content: `In compliance with the Portuguese Law (Article 10 of Decree-Law No. 7/2004, of January 7), we hereby inform:\n\nWebsite Owner: Ricardo André Silva Figueiredo\nVAT ID (NIF): 275331059\nAddress: Rua S. Miguel Roriz, n.º 1508, 4750-650 Barcelos, Portugal\nEmail: rikis.figueiredo@gmail.com\n\nIntellectual Property\nAll content present on this website - including images, texts, logos, and design - is the property of Concept and is protected by Portuguese and European copyright laws. Total or partial reproduction without prior authorization is strictly prohibited.\n\nLiability\nConcept is not responsible for damages resulting from the use of the website or the information contained therein. We reserve the right to change the content without prior notice.`
  },
  contact: {
    title: "Contact Us",
    content: `Have any questions, feedback, or need assistance with an order?\n\nWe are here to help!\n\nEmail: conceptclothing.pt@gmail.com\nAddress: Rua S. Miguel Roriz, n.º 1508, 4750-650 Barcelos, Portugal\n\nWe aim to respond to all inquiries within 24-48 business hours.`
  },
  cookies: {
    title: "Cookies Policy",
    content: `We use cookies to enhance your browsing experience, save items in your shopping cart, and analyze our website traffic.\n\nBy continuing to use this site, you consent to our use of cookies. You can manage or disable cookies at any time through your browser settings, but please note that some features of our store (like the shopping cart) may not function properly without them.`
  }
};